### ISSUE TITLE
Screen re-design

### ISSUE THREAD

**Issue by claycrews2002** [wordification/app#164]
Can add sketches for screen re-designs here if needed.

**Comment by ShashComandur** [comment]
# Notes from 2/15 Meeting
### Color Palette
TBD, but we were thinking about lighter pastel colors associated with children / education

### Pictures, Ilustrations, & Icons
We want to implement icons for each game, and eventually, would be nice to do so for every word, though this would be a huge undertaking. Potentially something to AI generate. We were also considering small JavaScript animations for each game icon.

### Card Element (for game select)
See Figma.

### Font Choice
[Gabarito](https://fonts.google.com/specimen/Gabarito?classification=Display&stroke=Sans+Serifl) was a compelling choice we found off of Google Fonts. We wanted to go with something that is easy on the eyes and readable as body text, but also appealing to children.

**Comment by ShashComandur** [comment]
# Notes from 3/22 Meeting

### Buttons Change Color
### Sound Effects based on answer correctness
